# Generated by Django 4.0.2 on 2022-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='имя категории')),
                ('category_id', models.IntegerField(max_length=15, verbose_name='id категории')),
            ],
        ),
    ]
