# Generated by Django 4.0.2 on 2022-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productcategory_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='имя продукта')),
                ('price', models.FloatField(verbose_name='цена')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=30, verbose_name='имя категории'),
        ),
    ]
