# Generated by Django 4.0.2 on 2022-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=30, null=True, verbose_name='категория'),
        ),
    ]
