# Generated by Django 4.0.2 on 2022-02-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category_alter_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
