# Generated by Django 4.0.2 on 2022-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_category_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='price',
            field=models.FloatField(null=True, verbose_name='цена'),
        ),
    ]
