# Generated by Django 4.0.2 on 2022-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productcategory_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='price',
        ),
    ]
