# Generated by Django 4.0.2 on 2022-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='image/', verbose_name='изображение'),
        ),
    ]
